import https from 'https';
import http from 'http';
import { URL } from 'url';
import type { RunAllResult } from './types';

export interface WebhookResponse {
  success: boolean;
  statusCode?: number;
  error?: string;
}

function postJson(targetUrl: string, data: Record<string, unknown>): Promise<WebhookResponse> {
  return new Promise((resolve) => {
    try {
      const parsedUrl = new URL(targetUrl);
      const postData = JSON.stringify(data);
      const isHttps = parsedUrl.protocol === 'https:';
      const client = isHttps ? https : http;

      const options = {
        hostname: parsedUrl.hostname,
        port: parsedUrl.port || (isHttps ? 443 : 80),
        path: `${parsedUrl.pathname}${parsedUrl.search}`,
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Content-Length': Buffer.byteLength(postData),
        },
      };

      const req = client.request(options, (res) => {
        let body = '';
        res.on('data', (chunk) => {
          body += chunk;
        });
        res.on('end', () => {
          const success =
            res.statusCode !== undefined && res.statusCode >= 200 && res.statusCode < 300;
          resolve({
            success,
            statusCode: res.statusCode,
            error: success ? undefined : body || `HTTP ${res.statusCode}`,
          });
        });
      });

      req.on('error', (err) => {
        resolve({ success: false, error: err.message });
      });

      req.write(postData);
      req.end();
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : String(err);
      resolve({ success: false, error: msg });
    }
  });
}

export function buildSlackPayload(result: RunAllResult, repoName: string): Record<string, unknown> {
  const needsFix = result.remediation.filter((r) => r.score < 5);
  const fixSummary =
    needsFix.length > 0
      ? needsFix
          .slice(0, 3)
          .map((r) => `• *${r.label}* (${r.score}/5)`)
          .join('\n')
      : 'All dimensions scored 5/5! Autonomous-ready.';

  return {
    text: `Agent Readiness Scan for ${repoName}: ${result.level.name} (${result.ceiling}/5)`,
    blocks: [
      {
        type: 'header',
        text: {
          type: 'plain_text',
          text: `🤖 Agent Readiness Report: ${repoName}`,
          emoji: true,
        },
      },
      {
        type: 'section',
        fields: [
          {
            type: 'mrkdwn',
            text: `*Readiness Level:*\n${result.level.name} (${result.ceiling}/5)`,
          },
          {
            type: 'mrkdwn',
            text: `*Readiness Index:*\n${result.indexScore}/100 (${result.grade})`,
          },
        ],
      },
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `*Priority Remediation:*\n${fixSummary}`,
        },
      },
      {
        type: 'context',
        elements: [
          {
            type: 'mrkdwn',
            text: 'Generated by <https://github.com/Praashh/repograder|repograder>',
          },
        ],
      },
    ],
  };
}

export function buildDiscordPayload(
  result: RunAllResult,
  repoName: string,
): Record<string, unknown> {
  const needsFix = result.remediation.filter((r) => r.score < 5);
  const color = result.ceiling >= 4 ? 3066993 : result.ceiling === 3 ? 16776960 : 15158332;

  const fields = [
    {
      name: 'Readiness Level',
      value: `${result.level.name} (${result.ceiling}/5)`,
      inline: true,
    },
    {
      name: 'Readiness Index',
      value: `${result.indexScore}/100 (${result.grade})`,
      inline: true,
    },
  ];

  if (needsFix.length > 0) {
    fields.push({
      name: 'Top Remediation Priorities',
      value: needsFix
        .slice(0, 3)
        .map((r) => `• **${r.label}** (${r.score}/5)`)
        .join('\n'),
      inline: false,
    });
  }

  return {
    embeds: [
      {
        title: `🤖 Agent Readiness Report: ${repoName}`,
        color,
        fields,
        footer: {
          text: 'repograder — AI agent readiness scoring',
        },
        timestamp: new Date().toISOString(),
      },
    ],
  };
}

export async function sendSlackNotification(
  webhookUrl: string,
  result: RunAllResult,
  repoName = 'Repository',
): Promise<WebhookResponse> {
  const payload = buildSlackPayload(result, repoName);
  return postJson(webhookUrl, payload);
}

export async function sendDiscordNotification(
  webhookUrl: string,
  result: RunAllResult,
  repoName = 'Repository',
): Promise<WebhookResponse> {
  const payload = buildDiscordPayload(result, repoName);
  return postJson(webhookUrl, payload);
}
