import type { RunAllResult } from './types';

const RESET = '\x1b[0m';
const BOLD = '\x1b[1m';
const DIM = '\x1b[2m';
const RED = '\x1b[31m';
const YELLOW = '\x1b[33m';
const GREEN = '\x1b[32m';
const CYAN = '\x1b[36m';

function colorForScore(score: number): string {
  if (score <= 2) return RED;
  if (score === 3) return YELLOW;
  return GREEN;
}

function hexColorForScore(score: number): string {
  if (score <= 2) return 'red';
  if (score === 3) return 'yellow';
  if (score === 4) return 'green';
  return 'brightgreen';
}

function bar(score: number, max = 5): string {
  const filled = '█'.repeat(score);
  const empty = '░'.repeat(max - score);
  return `${colorForScore(score)}${filled}${DIM}${empty}${RESET}`;
}

export function renderText(
  { results, ceiling, level, indexScore, grade, remediation }: RunAllResult,
  targetPath: string,
): string {
  const lines: string[] = [];
  lines.push('');
  lines.push(`${BOLD}Agent Readiness Scan${RESET}  ${DIM}${targetPath}${RESET}`);
  lines.push('');
  lines.push(
    `${BOLD}Readiness level: ${colorForScore(ceiling)}${level.name} (${ceiling}/5)${RESET}  ` +
      `${BOLD}Index: ${colorForScore(Math.round(indexScore / 20))}${indexScore}/100 (${grade})${RESET}  ` +
      `${DIM}— ceiling set by lowest dimension${RESET}`,
  );
  lines.push('');

  for (const r of results) {
    const flag = r.blocking ? `${DIM}[blocking]${RESET}` : '';
    lines.push(`  ${bar(r.score)}  ${BOLD}${r.score}/5${RESET}  ${r.label} ${flag}`);
    for (const line of r.evidence) {
      lines.push(`        ${DIM}${line}${RESET}`);
    }
    if (r.remediationTips && r.remediationTips.length > 0 && r.score < 5) {
      for (const tip of r.remediationTips) {
        lines.push(`        ${CYAN}↳ Fix: ${tip}${RESET}`);
      }
    }
    lines.push('');
  }

  lines.push(`${BOLD}${CYAN}Priority order for improvement:${RESET}`);
  const needsFix = remediation.filter((r) => r.score < 5);
  if (needsFix.length === 0) {
    lines.push(
      `  ${GREEN}All measured dimensions score 5/5. Repository is autonomous-ready!${RESET}`,
    );
  } else {
    needsFix.slice(0, 5).forEach((r, i) => {
      const tip = r.remediationTips && r.remediationTips[0] ? ` — ${r.remediationTips[0]}` : '';
      lines.push(
        `  ${i + 1}. ${BOLD}${r.label}${RESET} (currently ${r.score}/5)${r.blocking ? ' [blocking]' : ''}${tip}`,
      );
    });
  }
  lines.push('');

  return lines.join('\n');
}

export function renderJSON(
  { results, ceiling, level, indexScore, grade, remediation }: RunAllResult,
  targetPath: string,
): string {
  return JSON.stringify(
    {
      target: targetPath,
      scannedAt: new Date().toISOString(),
      readinessLevel: level.name,
      ceilingScore: ceiling,
      indexScore,
      grade,
      dimensions: results,
      remediationOrder: remediation.map((r) => ({
        id: r.id,
        score: r.score,
        blocking: r.blocking,
        remediationTips: r.remediationTips ?? [],
      })),
    },
    null,
    2,
  );
}

export function renderMarkdown(
  { results, ceiling, level, indexScore, grade, remediation }: RunAllResult,
  targetPath: string,
): string {
  const lines: string[] = [];
  lines.push('# 🤖 Agent Readiness Report');
  lines.push('');
  lines.push(`**Target**: \`${targetPath}\`  `);
  lines.push(`**Scanned at**: ${new Date().toUTCString()}  `);
  lines.push(
    `**Readiness Level**: **${level.name} (${ceiling}/5)** &nbsp;|&nbsp; **Readiness Index**: **${indexScore}/100 (${grade})**`,
  );
  lines.push('');
  lines.push(
    '> *Readiness level is governed by the Weakest Link Principle (minimum score across dimensions).*',
  );
  lines.push('');
  lines.push('### Score Breakdown');
  lines.push('');
  lines.push('| Dimension | Score | Status | Key Evidence |');
  lines.push('|:---|:---:|:---:|:---|');

  for (const r of results) {
    const icon = r.score >= 4 ? '✅' : r.score === 3 ? '⚠️' : '❌';
    const blockingBadge = r.blocking ? ' *(blocking)*' : '';
    const evidenceSummary = r.evidence.join('<br>');
    lines.push(`| **${r.label}**${blockingBadge} | ${r.score}/5 | ${icon} | ${evidenceSummary} |`);
  }

  lines.push('');
  lines.push('### 🛠️ Priority Remediation Actions');
  lines.push('');

  const needsFix = remediation.filter((r) => r.score < 5);
  if (needsFix.length === 0) {
    lines.push('🎉 **All measured dimensions score 5/5! Repository is autonomous-ready.**');
  } else {
    needsFix.forEach((r, i) => {
      const blockingNotice = r.blocking ? ' **[Blocking Dimension]**' : '';
      lines.push(`${i + 1}. **${r.label}** (Score: ${r.score}/5)${blockingNotice}`);
      if (r.remediationTips && r.remediationTips.length > 0) {
        for (const tip of r.remediationTips) {
          lines.push(`   - 💡 ${tip}`);
        }
      }
    });
  }

  lines.push('');
  lines.push('---');
  lines.push('*Generated by [repograder](https://github.com/Praashh/repograder)*');
  lines.push('');

  return lines.join('\n');
}

export function renderBadge({ ceiling, level }: RunAllResult): string {
  return JSON.stringify({
    schemaVersion: 1,
    label: 'agent readiness',
    message: `${level.name} (${ceiling}/5)`,
    color: hexColorForScore(ceiling),
  });
}

export function renderSARIF({ results }: RunAllResult, _targetPath: string): string {
  const rules = [];
  const sarifResults = [];

  for (const r of results) {
    const ruleId = `REPO-${r.id}`;
    rules.push({
      id: ruleId,
      name: r.id,
      shortDescription: {
        text: r.label,
      },
      fullDescription: {
        text: `Evaluates ${r.label} for AI coding agent readiness.`,
      },
      defaultConfiguration: {
        level: r.blocking || r.score <= 2 ? 'error' : r.score === 3 ? 'warning' : 'note',
      },
      help: {
        text:
          r.remediationTips && r.remediationTips.length > 0
            ? r.remediationTips.join('\n')
            : `Improve ${r.label} to achieve autonomous agent readiness.`,
      },
    });

    if (r.score < 5) {
      const level = r.blocking || r.score <= 2 ? 'error' : r.score === 3 ? 'warning' : 'note';
      const evidenceStr = r.evidence.join('; ');
      const tipStr =
        r.remediationTips && r.remediationTips.length > 0
          ? ` Remediation: ${r.remediationTips.join(' | ')}`
          : '';
      sarifResults.push({
        ruleId,
        level,
        message: {
          text: `[${r.label}] Score ${r.score}/5: ${evidenceStr}.${tipStr}`,
        },
        locations: [
          {
            physicalLocation: {
              artifactLocation: {
                uri: '.',
                uriBaseId: '%SRCROOT%',
              },
              region: {
                startLine: 1,
                startColumn: 1,
              },
            },
          },
        ],
      });
    }
  }

  const sarifLog = {
    $schema:
      'https://raw.githubusercontent.com/oasis-tcs/sarif-spec/master/Schemata/sarif-schema-2.1.0.json',
    version: '2.1.0',
    runs: [
      {
        tool: {
          driver: {
            name: 'repograder',
            version: '0.1.4',
            informationUri: 'https://github.com/Praashh/repograder',
            rules,
          },
        },
        results: sarifResults,
      },
    ],
  };

  return JSON.stringify(sarifLog, null, 2);
}

export function renderCodeClimate({ results }: RunAllResult, _targetPath: string): string {
  const issues = [];
  for (const r of results) {
    if (r.score < 5) {
      const severity =
        r.blocking || r.score <= 1
          ? 'blocker'
          : r.score === 2
            ? 'critical'
            : r.score === 3
              ? 'major'
              : 'minor';
      issues.push({
        type: 'issue',
        check_name: `repograder/${r.id}`,
        description: `[${r.label}] (Score ${r.score}/5): ${r.evidence[0] || 'Suboptimal score'}`,
        content: {
          body:
            r.remediationTips && r.remediationTips.length > 0
              ? r.remediationTips.map((t) => `- ${t}`).join('\n')
              : r.evidence.join('\n'),
        },
        categories: ['Bug Risk', 'Clarity'],
        severity,
        location: {
          path: '.',
          lines: {
            begin: 1,
          },
        },
      });
    }
  }
  return JSON.stringify(issues, null, 2);
}
